import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./(frontend)/components/SessionProviderWrapper";
import dynamic from "next/dynamic";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login system",
  description: "Generated by create next app",
};

// Dynamically import ToastContainer with SSR disabled
const ToastContainer = dynamic(
  () => import('react-toastify').then((mod) => mod.ToastContainer),
  { ssr: false }
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
        <ToastContainer />
      </body>
    </html>
  );
}
